apiVersion: v1
kind: Pod
metadata:
  name: teamcity
  labels:
    app: teamcity
spec:
  restartPolicy: Always
  containers:
    - name: teamcity
      image: jetbrains/teamcity-server
      ports:
        - name: teamcity
          containerPort: 8111
      resources:
        limits:
          memory: "2Gi"
