apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity
  namespace: tc
  labels:
    app: teamcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity
  template:
    metadata:
      namespace: tc
      labels:
        app: teamcity
    spec:
      restartPolicy: Always
      serviceAccountName: teamcity 
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server
          ports:
            - name: dashboard
              containerPort: 8111
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
