kind: Service
apiVersion: v1
metadata:
  name: teamcity-service
  namespace: tc
  labels:
    app: teamcity
spec:
  selector:
    app: teamcity
  type: LoadBalancer
  ports:
  - name: dashboardlb
    port: 8111
    targetPort: 8111